spring:
  application:
    name: user-app
  config:
    import: optional:configserver:http://localhost:8900
  profiles:
    active: local
  r2dbc:
    username: lamya
    password: UserPass@123
server:
  forward-headers-strategy: native
management:
  endpoints:
     web:
       exposure:
           include: *