version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password@123
      MYSQL_DATABASE: library
      MYSQL_USER: lamya
      MYSQL_PASSWORD: UserPass@123
    ports:
      - 3306:3306
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080